//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplainDetail
    {
        public int ComplainId { get; set; }
        public Nullable<int> Empid { get; set; }
        public Nullable<int> ComplainTypeId { get; set; }
        public Nullable<int> ComplainSubTypeId { get; set; }
        public Nullable<int> UlbID { get; set; }
        public Nullable<int> RegId { get; set; }
        public string ComplainNo { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string AadharNo { get; set; }
        public string Address { get; set; }
        public string Pin { get; set; }
        public string Complain_Detail { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<int> ComplainStatus { get; set; }
        public string ExecRemark { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserRemark { get; set; }
    }
}
