//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TimeSheetEntities : DbContext
    {
        public TimeSheetEntities()
            : base("name=TimeSheetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ComplainDetail> ComplainDetails { get; set; }
        public virtual DbSet<ComplainLog> ComplainLogs { get; set; }
        public virtual DbSet<ComplainType> ComplainTypes { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Emp_Type> Emp_Type { get; set; }
        public virtual DbSet<EmployeeDeatil> EmployeeDeatils { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectModule> ProjectModules { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<SalarySlipInfo> SalarySlipInfoes { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<SubCompainType> SubCompainTypes { get; set; }
        public virtual DbSet<TaskDetail> TaskDetails { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TimeSheetDtl> TimeSheetDtls { get; set; }
        public virtual DbSet<ULB> ULBs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<vw_Complain_Dtl> vw_Complain_Dtl { get; set; }
        public virtual DbSet<vw_Complain_Sub_Type> vw_Complain_Sub_Type { get; set; }
        public virtual DbSet<vw_Project_Details> vw_Project_Details { get; set; }
        public virtual DbSet<vw_REPORT_COMPLAIN> vw_REPORT_COMPLAIN { get; set; }
        public virtual DbSet<vw_REPORT_COMPLAIN_Month> vw_REPORT_COMPLAIN_Month { get; set; }
        public virtual DbSet<vw_Task_Dtl> vw_Task_Dtl { get; set; }
        public virtual DbSet<vw_Timesheet_Dtl> vw_Timesheet_Dtl { get; set; }
        public virtual DbSet<vw_user_detail> vw_user_detail { get; set; }
        public virtual DbSet<vw_complain_avg_time_calculator> vw_complain_avg_time_calculator { get; set; }
    
        public virtual ObjectResult<sp_Log_Detail_Result> sp_Log_Detail(Nullable<int> compid)
        {
            var compidParameter = compid.HasValue ?
                new ObjectParameter("compid", compid) :
                new ObjectParameter("compid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Log_Detail_Result>("sp_Log_Detail", compidParameter);
        }
    
        public virtual ObjectResult<sp_REPORT_COMPLAIN_Year_Result> sp_REPORT_COMPLAIN_Year(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_REPORT_COMPLAIN_Year_Result>("sp_REPORT_COMPLAIN_Year", yearParameter);
        }
    }
}
