//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalarySlipInfo
    {
        public int Slipid { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeCode { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string Region { get; set; }
        public string BankName { get; set; }
        public Nullable<int> BankAccountNO { get; set; }
        public string UAN { get; set; }
        public Nullable<int> PayableDays { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public string PFNO { get; set; }
        public string EsicNumber { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> HouserentAllow { get; set; }
        public Nullable<decimal> ConveyanceAllow { get; set; }
        public Nullable<decimal> MedicalAllow { get; set; }
        public Nullable<decimal> SpecialAllownce { get; set; }
        public Nullable<decimal> PerformancePay { get; set; }
        public Nullable<decimal> GrossEarning { get; set; }
        public Nullable<decimal> OtherEarning { get; set; }
        public Nullable<decimal> TotalGrossEarning { get; set; }
        public Nullable<decimal> ProvidentFund { get; set; }
        public Nullable<decimal> ProfessionalTax { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> ESI { get; set; }
        public Nullable<decimal> TrustDeduction { get; set; }
        public Nullable<decimal> OtherDeduction { get; set; }
        public Nullable<decimal> LeaveDeduction { get; set; }
        public Nullable<decimal> GrossDeduction { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<int> SickLeave { get; set; }
        public Nullable<int> CasualLeave { get; set; }
        public Nullable<int> AnnualLeave { get; set; }
        public Nullable<int> LeaveTaken { get; set; }
        public Nullable<int> AllowedLeave { get; set; }
        public Nullable<int> LopDays { get; set; }
        public Nullable<int> LeaveBalance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modifyon { get; set; }
        public string ModifyBy { get; set; }
    }
}
