//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int TaskId { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionName { get; set; }
        public Nullable<System.DateTime> TranCreationDate { get; set; }
        public string AssignedTaskDetail { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApprived { get; set; }
    }
}
