//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Complain_Sub_Type
    {
        public string ComplainName { get; set; }
        public string SubtypeName { get; set; }
        public int CompainsubtypeId { get; set; }
    }
}
