//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_complain_avg_time_calculator
    {
        public string PriorityHigh { get; set; }
        public Nullable<int> avgtime_high { get; set; }
        public string PriorityMedium { get; set; }
        public Nullable<int> avgtime_med { get; set; }
        public string PriorityLow { get; set; }
        public Nullable<int> avgtime_low { get; set; }
    }
}
