//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Complain_Dtl
    {
        public int ComplainId { get; set; }
        public Nullable<int> ComplainTypeId { get; set; }
        public string ComplainName { get; set; }
        public string ComplainNo { get; set; }
        public Nullable<int> RegId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string AadharNo { get; set; }
        public string Complain_Detail { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public string Pin { get; set; }
        public string ComPriority { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public string rcvname { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Receive_Date { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Assigned_Date { get; set; }
        public string assnname { get; set; }
        public Nullable<int> ComplainStatus { get; set; }
        public string StatusName { get; set; }
        public string ExecRemark { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Action_Date { get; set; }
        public Nullable<int> UlbID { get; set; }
        public string ULBName { get; set; }
        public int ComplainSubTypeId { get; set; }
        public string SubtypeName { get; set; }
        public string UserRemark { get; set; }
        public Nullable<int> Empid { get; set; }
        public string EmpType { get; set; }
    }
}
