//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_REPORT_COMPLAIN_Month
    {
        public int UlbID { get; set; }
        public string ULBName { get; set; }
        public Nullable<int> mTotal { get; set; }
        public Nullable<int> mAssigned { get; set; }
        public Nullable<int> mResolved { get; set; }
        public Nullable<int> mRejected { get; set; }
        public Nullable<int> mReopen { get; set; }
        public Nullable<int> mClose { get; set; }
        public Nullable<int> mPending { get; set; }
    }
}
