//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_REPORT_COMPLAIN
    {
        public int UlbID { get; set; }
        public string ULBName { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Assigned { get; set; }
        public Nullable<int> Resolved { get; set; }
        public Nullable<int> Rejected { get; set; }
        public Nullable<int> Reopen { get; set; }
        public Nullable<int> Close { get; set; }
        public Nullable<int> Pending { get; set; }
    }
}
