//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Task_Dtl
    {
        public int TaskId { get; set; }
        public string DistrictName { get; set; }
        public string ProjectName { get; set; }
        public string Module { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionName { get; set; }
        public string AssignedTaskDetail { get; set; }
        public string TranCreationDate { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> assignid { get; set; }
        public string Assugn_name { get; set; }
        public Nullable<bool> IsApprived { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> trncreatedate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ModuleId { get; set; }
    }
}
