//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Timesheet_Dtl
    {
        public int TimesheetId { get; set; }
        public string DistrictName { get; set; }
        public string ProjectName { get; set; }
        public string Module { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionName { get; set; }
        public string TransactionDesc { get; set; }
        public string TranCreationDate { get; set; }
        public string TranPostDate { get; set; }
        public string PendingReason { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public string TLName { get; set; }
        public Nullable<int> tlid { get; set; }
        public string TLRemark { get; set; }
        public string PMName { get; set; }
        public Nullable<int> pmid { get; set; }
        public string PMRemark { get; set; }
        public Nullable<bool> IsApprived { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> trncreatedate { get; set; }
        public Nullable<System.DateTime> trnpostdate { get; set; }
        public string TaskDetail { get; set; }
    }
}
