//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTimesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_user_detail
    {
        public int RegistrationId { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Contactno { get; set; }
        public string DistrictName { get; set; }
        public string UserTypeName { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> ComplainTypeId { get; set; }
        public string ComplainName { get; set; }
        public Nullable<int> UlbID { get; set; }
        public string ULBName { get; set; }
    }
}
